export default [
    {
        id: "1",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Come Here',
        artist: 'Dominic Fike',
        track: '1/14',
        time: '2:16',
        rating: 'mid',
    },
    {
        id: "2",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Double Negative (Skeleton Milkshake)',
        artist: 'Dominic Fike',
        track: '2/14',
        time: '3:09',
        rating: 'mid',
    },
    {
        id: "3",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Cancel Me',
        artist: 'Dominic Fike',
        track: '3/14',
        time: '2:41',
        rating: 'good',
    },
    {
        id: "4",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: '10x Stronger',
        artist: 'Dominic Fike',
        track: '4/14',
        time: '3:19',
        rating: 'good',
    },
    {
        id: "5",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Good Game',
        artist: 'Dominic Fike',
        track: '5/14',
        time: '2:57',
        rating: 'mid',
    },
    {
        id: "6",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Why',
        artist: 'Dominic Fike',
        track: '6/14',
        time: '2:18',
        rating: 'good',
    },
    {
        id: "7",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Chicken Tenders',
        artist: 'Dominic Fike',
        track: '7/14',
        time: '2:25',
        rating: 'good',
    },
    {
        id: "8",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Whats for Dinner?',
        artist: 'Dominic Fike',
        track: '8/14',
        time: '1:29',
        rating: 'good',
    },
    {
        id: "9",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Vampire',
        artist: 'Dominic Fike',
        track: '9/14',
        time: '2:16',
        rating: 'good',
    },
    {
        id: "10",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Superstar Sh*t',
        artist: 'Dominic Fike',
        track: '10/14',
        time: '2:14',
        rating: 'GodTier',
    },
    {
        id: "11",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Politics & Violence',
        artist: 'Dominic Fike',
        track: '11/14',
        time: '2:14',
        rating: 'GodTier',
    },
    {
        id: "12",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Joe Blazey',
        artist: 'Dominic Fike',
        track: '12/14',
        time: '2:35',
        rating: '',
    },
    {
        id: "13",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Wurli',
        artist: 'Dominic Fike',
        track: '13/14',
        time: '3:39',
        rating: 'good',
    },
    {
        id: "14",
        img: 'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mohe7l1uk9ewuqfgw0dh/dominic-fike',
        title: 'Florida',
        artist: 'Dominic Fike',
        track: '14/14',
        time: '3:08',
        rating: 'mid',
    },
];