export default [
    {
        id: "1",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Nikes',
        artist: 'Frank Ocean',
        track: '1/17',
        time: '5:13',
        rating: 'good',
    },
    {
        id: "2",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Ivy',
        artist: 'Frank Ocean',
        track: '2/17',
        time: '4:09',
        rating: 'good',
    },
    {
        id: "3",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Pink + White',
        artist: 'Frank Ocean',
        track: '3/17',
        time: '3:04',
        rating: 'good',
    },
    {
        id: "4",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Be Yourself',
        artist: 'Frank Ocean',
        track: '4/17',
        time: '1:29',
        rating: 'skit',
    },
    {
        id: "5",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Solo',
        artist: 'Frank Ocean',
        track: '5/17',
        time: '4:17',
        rating: 'GodTier',
    },
    {
        id: "6",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Skyline To',
        artist: 'Frank Ocean',
        track: '6/17',
        time: '3:04',
        rating: 'mid',
    },
    {
        id: "7",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Self Control',
        artist: 'Frank Ocean',
        track: '7/17',
        time: '4:09',
        rating: 'good',
    },
    {
        id: "8",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Good Guy',
        artist: 'Frank Ocean',
        track: '8/17',
        time: '1:07',
        rating: 'mid',
    },
    {
        id: "9",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Nights',
        artist: 'Frank Ocean',
        track: '9/17',
        time: '5:07',
        rating: 'GodTier',
    },
    {
        id: "10",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Solo (Reprise)',
        artist: 'Frank Ocean feat. André 3000',
        track: '10/17',
        time: '1:19',
        rating: 'GodTier',
    },
    {
        id: "11",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Pretty Sweet',
        artist: 'Frank Ocean',
        track: '11/17',
        time: '2:38',
        rating: 'bad',
    },
    {
        id: "12",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Facebook Story',
        artist: 'Frank Ocean',
        track: '12/17',
        time: '0:49',
        rating: 'skit',
    },
    {
        id: "13",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Close to You',
        artist: 'Frank Ocean',
        track: '13/17',
        time: '1:25',
        rating: 'bad',
    },
    {
        id: "14",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'White Ferrari',
        artist: 'Frank Ocean',
        track: '14/17',
        time: '4:09',
        rating: 'good',
    },
    {
        id: "15",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Seigfried',
        artist: 'Frank Ocean',
        track: '15/17',
        time: '5:34',
        rating: 'bad',
    },
    {
        id: "16",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Godspeed',
        artist: 'Frank Ocean',
        track: '16/17',
        time: '2:57',
        rating: 'good',
    },
    {
        id: "17",
        img: 'https://th.bing.com/th/id/OIP.V3fEyW1lhaE-vNIUWIzvrAHaHa?pid=ImgDet&rs=1',
        title: 'Futura Free',
        artist: 'Frank Ocean',
        track: '17/17',
        time: '9:24',
        rating: 'mid',
    },
];
