export default [
    {
        id: "1",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'SIR BAUDELAIRE',
        artist: 'Tyler, the Creator',
        track: '1/16',
        time: '1:46',
        rating: 'mid',
    },
    {
        id: "2",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'CORSO',
        artist: 'Tyler, the Creator',
        track: '2/16',
        time: '4:35',
        rating: 'GodTier',
    },
    {
        id: "3",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'LEMONHEAD',
        artist: 'Tyler, the Creator, Pharrell Williams',
        track: '3/16',
        time: '2:45',
        rating: 'mid',
    },
    {
        id: "4",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'WUSYANAME',
        artist: 'Tyler, the Creator, Ty Dolla $ign, Tyga',
        track: '4/16',
        time: '2:30',
        rating: 'good',
    },
    {
        id: "5",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'LUMBERJACK',
        artist: 'Tyler, the Creator',
        track: '5/16',
        time: '2:38',
        rating: 'GodTier',
    },
    {
        id: "6",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'HOT WIND BLOWS',
        artist: 'Tyler, the Creator, Lil Wayne',
        track: '6/16',
        time: '4:09',
        rating: 'good',
    },
    {
        id: "7",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'MASSA',
        artist: 'Tyler, the Creator',
        track: '7/16',
        time: '3:21',
        rating: 'good',
    },
    {
        id: "8",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'RUNITUP',
        artist: 'Tyler, the Creator, Teezo Touchdown',
        track: '8/16',
        time: '3:45',
        rating: 'good',
    },
    {
        id: "9",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'MANIFESTO',
        artist: 'Tyler, the Creator, Domo Genesis',
        track: '9/16',
        time: '4:18',
        rating: 'good',
    },
    {
        id: "10",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'SWEET / I THOUGHT YOU WANTED TO DANCE',
        artist: 'Tyler, the Creator, Brent Faiyaz, Fana Hues',
        track: '10/16',
        time: '5:29',
        rating: 'bad',
    },
    {
        id: "11",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'MOMMA TALK',
        artist: 'Tyler, the Creator',
        track: '11/16',
        time: '1:51',
        rating: 'skit',
    },
    {
        id: "12",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'RISE!',
        artist: 'Tyler, the Creator, DAISY WORLD',
        track: '12/16',
        time: '2:59',
        rating: 'good',
    },
    {
        id: "13",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'BLESSED',
        artist: 'Tyler, the Creator',
        track: '13/16',
        time: '2:35',
        rating: 'skit',
    },
    {
        id: "14",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'JUGGERNAUT',
        artist: 'Tyler, the Creator, Lil Uzi Vert, Pharrell Williams',
        track: '14/16',
        time: '2:59',
        rating: 'good',
    },
    {
        id: "15",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'WILSHIRE',
        artist: 'Tyler, the Creator',
        track: '15/16',
        time: '3:36',
        rating: 'good',
    },
    {
        id: "16",
        img: 'https://unfspinnaker.com/wp-content/uploads/2021/07/call-me-if-you-get-lost-1.png', 
        title: 'SAFARI',
        artist: 'Tyler, the Creator',
        track: '16/16',
        time: '2:57',
        rating: 'good',
    },
];
