export default [
    {
        id: "1",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Ultralight Beam',
        artist: 'Kanye West',
        track: '1/20',
        time: '5:12',
        rating: 'good',
    },
    {
        id: "2",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Father Stretch My Hands, Pt. 1',
        artist: 'Kanye West',
        track: '2/20',
        time: '2:15',
        rating: 'GodTier',
    },
    {
        id: "3",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Pt. 2',
        artist: 'Kanye West',
        track: '3/20',
        time: '2:10',
        rating: 'good',
    },
    {
        id: "4",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Famous',
        artist: 'Kanye West',
        track: '4/20',
        time: '3:16',
        rating: 'good',
    },
    {
        id: "5",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Feedback',
        artist: 'Kanye West',
        track: '5/20',
        time: '2:35',
        rating: 'good',
    },
    {
        id: "6",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Low Lights',
        artist: 'Kanye West',
        track: '6/20',
        time: '2:11',
        rating: 'mid',
    },
    {
        id: "7",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Highlights',
        artist: 'Kanye West',
        track: '7/20',
        time: '3:19',
        rating: 'good',
    },
    {
        id: "8",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Freestyle 4',
        artist: 'Kanye West',
        track: '8/20',
        time: '2:03',
        rating: 'bad',
    },
    {
        id: "9",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'I Love Kanye',
        artist: 'Kanye West',
        track: '9/20',
        time: '0:44',
        rating: 'skit',
    },
    {
        id: "10",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Waves',
        artist: 'Kanye West',
        track: '10/20',
        time: '3:01',
        rating: 'GodTier',
    },
    {
        id: "11",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'FML',
        artist: 'Kanye West',
        track: '11/20',
        time: '3:56',
        rating: 'good',
    },
    {
        id: "12",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Real Friends',
        artist: 'Kanye West',
        track: '12/20',
        time: '4:11',
        rating: 'mid',
    },
    {
        id: "13",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Wolves',
        artist: 'Kanye West',
        track: '13/20',
        time: '5:01',
        rating: 'GodTier',
    },
    {
        id: "14",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: "Frank's Track",
        artist: 'Kanye West',
        track: '14/20',
        time: '0:38',
        rating: 'good',
    },
    {
        id: "15",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Siiiiiiiiilver Surffffeeeeer Intermission',
        artist: 'Kanye West',
        track: '15/20',
        time: '0:56',
        rating: 'skit',
    },
    {
        id: "16",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: '30 Hours',
        artist: 'Kanye West',
        track: '16/20',
        time: '5:25',
        rating: 'good',
    },
    {
        id: "17",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'No More Parties in LA',
        artist: 'Kanye West',
        track: '17/20',
        time: '6:15',
        rating: 'GodTier',
    },
    {
        id: "18",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Facts (Charlie Heat Version)',
        artist: 'Kanye West',
        track: '18/20',
        time: '3:20',
        rating: 'good',
    },
    {
        id: "19",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Fade',
        artist: 'Kanye West',
        track: '19/20',
        time: '3:09',
        rating: 'mid',
    },
    {
        id: "20",
        img: 'https://i.redd.it/puu7vsw10fb01.png',
        title: 'Saint Pablo',
        artist: 'Kanye West',
        track: '20/20',
        time: '6:12',
        rating: 'good',
    },
];
